### ISSUE TITLE
Hide Indicator Unless 2 Workspaces 

### ISSUE THREAD

**Issue by hexive** [MichaelAquilina/improved-workspace-indicator#1]
Thanks for this extension!

I'm hoping to modify the extension.js to only show workspace indicators when there is more than 1 desktop. Is there an easy way to make this change? 

I thought maybe the show_or_hide function might be the place to look, but I don't really speak javascript. 

Thanks for your time!

**Comment by MichaelAquilina** [comment]
Hi @hexive. 

I've given the code a quick look and right now there doesnt seem to be an _obvious_ location to add this. `show_and_hide` is a method for `WorkspaceIndicator` only has context for a single workspace. You would probably want to add a similar `show_and_hide` method to `WorkspaceLayout` that checks the number of active workspaces and shows/hides accordingly.

I would say if you want to contribute this change upstream to make it an optional preference. It should be fairly easy to figure that out by taking a look at how the `panel-position` option works https://github.com/MichaelAquilina/improved-workspace-indicator/blob/2a93dbc35970b7274d620bcc0816666600487f63/extension.js#L123

Hope this helps you!

**Comment by hexive** [comment]
Thanks for the tips!
