### ISSUE TITLE
suggestion: enable center positioning on panel

### ISSUE THREAD

**Issue by ghost** [MichaelAquilina/improved-workspace-indicator#12]
hey there, great extension!

currently this extension can be set to be either right or left side on the panel.
i would appreciate the option of a central position.

thanks for consideration :)

**Comment by MichaelAquilina** [comment]
Hello @Earthling-Z3R0 :)

I think this change should actually be really easy. Would you be willing to try it out yourself?

**Comment by ghost** [comment]
I am not a coder. I tried messing with the files that have "left" and "right" in them but I failed miserably :o)
I am just a plain user loving this extension. It's by far the best workspace switcher imho.

**Comment by ghost** [comment]
On a sidenote: I managed to adjust the css to my preference though (-:

![screenshot_2022-02-14_16-01-19](https://user-images.githubusercontent.com/64461876/153888763-121e4d4e-95fc-4d49-bb57-fcc0d16d3511.png)

**Comment by MichaelAquilina** [comment]
Dw then I'll find some time to do it at some point :) should be a very easy change to get across as long as gnome provides support for it.

Nice job on the CSS! Stlying preferences might be something I am towards in the future too :)

**Comment by MichaelAquilina** [comment]
In case you are curious, this is what was needed: https://github.com/MichaelAquilina/improved-workspace-indicator/commit/e7ae3d513ab7c45bb6dd4a2f0a3694690b4a9d7b

I've uploading a version 9 for review which includes this feature.

Should be available as soon as a gnome developer reviews the change. Hope you enjoy it!
