### ISSUE TITLE
Mark extension as Gnome 43 compatible

### ISSUE THREAD

**Issue by rodrigogonegit** [MichaelAquilina/improved-workspace-indicator#20]
Hey, I have been using it for a couple of days and it seems to be fully compatible with Gnome 43.

**Comment by MichaelAquilina** [comment]
Hello :) thanks for letting me know. Would you like to open a PR to mark this? The change is quite easy. I am away from my laptop for a few days but happy to merge it in the meanwhile

**Comment by MichaelAquilina** [comment]
Fixed in latest version
