### ISSUE TITLE
Gnome 45

### ISSUE THREAD

**Issue by galen1423** [MichaelAquilina/improved-workspace-indicator#34]
Hello,

Thanks for this very useful extension to me. Consider you to port Workspace indicator to Gnome Shell 45 in a near future?

Thank you again for your work.

Regards

**Comment by Neo-29** [comment]
This extension was a must
Even if we have now a visual workspace indicator, it's not the same usage

**Comment by MichaelAquilina** [comment]
Hello :) I dont have gnome 45 installed on my Fedora box yet so I could not confirm if this is working.

Usually I just wait for someone to test it and update the `metadata.json` file themselves. 

I could release a new version and assume its working (nothing should have broken) and then you could let me know in this issue if you ran into any issues.

Would that work?

**Comment by Neo-29** [comment]
> Hello :) I dont have gnome 45 installed on my Fedora box yet so I could not confirm if this is working.
> 
> Usually I just wait for someone to test it and update the `metadata.json` file themselves.
> 
> I could release a new version and assume its working (nothing should have broken) and then you could let me know in this issue if you ran into any issues.
> 
> Would that work?

That could do for me. 👍

**Comment by MichaelAquilina** [comment]
there should be an update you can download soon

**Comment by galen1423** [comment]
https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

**Comment by MichaelAquilina** [comment]
ah so its not just a simple bump :)

**Comment by galen1423** [comment]
So, no... maybe there is a little work ahead. ^^

**Comment by MichaelAquilina** [comment]
doesnt look too difficult but I do have some questions around how backwards compatible with other versions this is. So I will need to find a free evening at some point.

This makes it harder to test without a Gnome 45 machine so I might have to wait for Fedora to release it or spend some time setting up a virtual machine.

**Comment by galen1423** [comment]
Ubuntu and Arch already have GS 45. Fedora 39 daily builds have too. Into a Virtual Machine, its working like a charm.

**Comment by MichaelAquilina** [comment]
yep, my question is more around how well these changes with older versions of gnome. So might have to either do some reading or testing on older versions.

Either way, more work than I thought it would be initially so just means i need to find some time to do it.

Feel free to give it a go if you want, shouldnt be too difficult to pick up :)
