### ISSUE TITLE
Themes and colord

### ISSUE THREAD

**Issue by bccoutinho** [MichaelAquilina/improved-workspace-indicator#4]
Is there a way o change the colors? It doesn't follow my theme.

**Comment by MichaelAquilina** [comment]
Currently - no

Although its not a hard change to add in theory.

I cant promise I will have the time to add this any time soon but I might eventually add it.

If you are feeling brave, you could probably figure out the required code changes yourself and open a PR :)

**Comment by bccoutinho** [comment]
Thank you for the good work. Changing the colors to the colors I want using the source code looks easy. I also don't know how make it automatic. If I have time I will look into it.

**Comment by rigopoui** [comment]
Thanks for enlightening me. I didn't know gnome extensions were just JS :) I edited mine to this.
![image](https://user-images.githubusercontent.com/45214361/178760395-bf25064b-67c9-4e7e-af9e-806b054216f7.png)

**Comment by n-patiphon** [comment]
@rigopoui That looks really cool! Would you mind sharing how you did it?
