### ISSUE TITLE
Ability to ignore DING window in workspaces

### ISSUE THREAD

**Issue by ShrirajHegde** [MichaelAquilina/improved-workspace-indicator#5]
Is it possible to put this left to the clock? The real estate of the top bar at the right of the clock is very crowded, so option to have the exact same thing on the left would be great.

**Comment by ShrirajHegde** [comment]
NVM I found the option, I didn't see it was there

**Comment by ShrirajHegde** [comment]
Ignoring DING windows would be great

**Comment by MichaelAquilina** [comment]
Duplicated by #3
